name: bcc321_tp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  animations: ^2.0.8
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^11.1.2
  intl: ^0.18.1
  mask_text_input_formatter: ^2.5.0
  supabase_flutter: ^1.10.21

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
