import 'package:flutter/material.dart';

class AppTextTheme {
  static const String fontFamily = 'Poppins';

  static const TextTheme textTheme = TextTheme(
    bodyLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodyMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 14,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodySmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 12,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.4,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 96,
      fontWeight: FontWeight.w300,
      inherit: false,
      letterSpacing: -1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 60,
      fontWeight: FontWeight.w300,
      inherit: false,
      letterSpacing: -0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displaySmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 48,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 40,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 34,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 24,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 14,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 1.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 11,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 10,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 20,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 14,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 0.1,
      textBaseline: TextBaseline.alphabetic,
    ),
  );
}
